### ISSUE TITLE
Failed to generate FHIR R4 with JSON.parse error

### ISSUE THREAD

**Issue by fff** [artifacthealth/fhir-dts-generator#2]
> Running "execute:generate" (execute) task
-> executing /fhir-dts-generator/build/src/main.js
Loading specification in /fhir-dts-generator/specification/fhir-spec
/fhir-dts-generator/specification/fhir-spec/R4/backbone-elements.json: Unexpected token ﻿ in JSON at position 0
/fhir-dts-generator/specification/fhir-spec/R4/choice-elements.json: Unexpected token ﻿ in JSON at position 0
undefined:1
﻿{
^
SyntaxError: Unexpected token ﻿ in JSON at position 0
at JSON.parse (<anonymous>)
at /fhir-dts-generator/build/src/main.js:38:28
at Array.forEach (<anonymous>)
at createDeclarationTests (/fhir-dts-generator/build/src/main.js:37:56)
at Object.<anonymous> (/fhir-dts-generator/build/src/main.js:28:1)

` node -v
v10.12.0
`

` npm -v
6.9.0
`

**Comment by meirgottlieb** [comment]
This is expected. I have not updated the generator for R4 and don't plan to anytime soon. If you decide to update for R4, please submit a pull request. Other people have requested the R4 update as well. Thanks!
